### ISSUE TITLE
Clarification

### ISSUE THREAD

**Issue by azzaea** [samuelbfernandes/simplePHENOTYPES#1]
Hi!
Thank you for developing this package and making it available. 
I'm a bit uncertain about how different genetic effects are simulated per [table 1 of simplePHENOTYPES preprint](https://www.biorxiv.org/content/10.1101/2020.01.11.902874v2.full#T1). In particular:
1. In this table, the genotypic values `-1, 0, 1` correspond to dosages: `0,1,2` typically used, correct?
1. For simulating dominance, I was expecting both the `0` and `1` genotypes to have `d` effect, but this is not the case, could you explain?
2. What does the second column in this table mean? Is it the genotype of the other epistatic QTL?

Again, thank you for developing this package, and also your help clarifying the issues above.

Best,
Azza

**Comment by samuelbfernandes** [comment]
Dear Azza,

Thank you for using simplePHENOTYPES.

As for your questions, please see below:
1: Yes. The way we code it is as follows: -1 = “aa”, 0 = “Aa”, and 1 = “AA” .
2: I agree that under additive and dominance (complete dominance) model, both AA and Aa will have the same genetic effect. If the model is exclusively dominant, on the other hand, only the heterozygote will have a non-zero effect.
Please see model 2 of Zeng and Zou (2005) (https://www.genetics.org/content/169/3/1711).
3: Yes, those are the genotypes for the epistatic model. For instance, the epistatic QTN with genotypes [-1 and 1], it’ll assign the effect “-e”.

Best regards,
Samuel
